version: '3.9'

services:
  app:
    build: .
    expose:
      - "9000"  # Laravel работает на порту PHP-FPM
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/var/www/html  # Монтируем проект внутрь контейнера
      - ./static:/var/www/html/public/static  # Пример для статических файлов

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: publishing
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5442"  # Подключение к PostgreSQL через порт 5434
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - app-network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Конфигурация NGINX
      - .:/var/www/html  # Прокси NGINX к Laravel-приложению
    ports:
      - "8080:80"  # NGINX будет доступен на порту 8080
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
